@php($editing = $goal !== null)
<form method="POST" action="{{ $action }}" class="grid gap-4 sm:grid-cols-2">
    @csrf
    @if($method !== 'POST') @method($method) @endif
    <input type="hidden" name="period_anchor" value="{{ $goal?->period_start?->toDateString() ?? $period['anchor'] }}">
    <label class="sm:col-span-2"><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Goal name') }}</span><input name="name" required maxlength="160" value="{{ old('name', $goal?->name) }}" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label class="sm:col-span-2"><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Description') }}</span><textarea name="description" rows="2" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">{{ old('description', $goal?->description) }}</textarea></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Period') }}</span><select name="period_type" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach(\App\Models\Goal::periodTypes() as $type)<option value="{{ $type }}" @selected(old('period_type', $goal?->period_type ?? $period['type']) === $type)>{{ __(ucfirst($type)) }}</option>@endforeach</select></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Tracking') }}</span><select name="tracking_mode" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="automatic" @selected(old('tracking_mode', $goal?->tracking_mode) === 'automatic')>{{ __('Automatic') }}</option><option value="manual" @selected(old('tracking_mode', $goal?->tracking_mode ?? 'manual') === 'manual')>{{ __('Manual') }}</option></select></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Automatic metric') }}</span><select name="metric_key" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">{{ __('None / manual') }}</option>@foreach($metricDefinitions as $key => $definition)<option value="{{ $key }}" @selected(old('metric_key', $goal?->metric_key) === $key)>{{ $definition['label'] }}</option>@endforeach</select></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Unit') }}</span><select name="unit" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach(\App\Models\Goal::UNITS as $unit)<option value="{{ $unit }}" @selected(old('unit', $goal?->unit ?? 'orders') === $unit)>{{ __(ucfirst($unit)) }}</option>@endforeach</select></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Target value') }}</span><input type="number" step="0.01" min="0" name="target_value" required value="{{ old('target_value', $goal?->target_value) }}" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Priority') }}</span><select name="priority" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950">@foreach(\App\Models\Goal::PRIORITIES as $priority)<option value="{{ $priority }}" @selected(old('priority', $goal?->priority ?? 'medium') === $priority)>{{ __(ucfirst($priority)) }}</option>@endforeach</select></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Start date') }}</span><input type="date" name="start_date" required value="{{ old('start_date', $goal?->start_date?->toDateString() ?? $period['start']->toDateString()) }}" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Deadline') }}</span><input type="date" name="deadline" required value="{{ old('deadline', $goal?->deadline?->toDateString() ?? $period['display_end']->toDateString()) }}" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Reward points') }}</span><input type="number" min="0" name="reward_points" required value="{{ old('reward_points', $goal?->reward_points ?? 100) }}" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></label>
    <div class="hidden sm:block"></div>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Category filter') }}</span><select name="category_id" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">{{ __('All categories') }}</option>@foreach($categories as $item)<option value="{{ $item->id }}" @selected((string) old('category_id', data_get($goal?->metric_config, 'category_id', '')) === (string) $item->id)>{{ $item->localizedName() }}</option>@endforeach</select></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Product brand filter') }}</span><select name="product_brand_id" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">{{ __('All product brands') }}</option>@foreach($productBrands as $item)<option value="{{ $item->id }}" @selected((string) old('product_brand_id', data_get($goal?->metric_config, 'product_brand_id', '')) === (string) $item->id)>{{ $item->name }}</option>@endforeach</select></label>
    <label><span class="text-sm font-semibold text-slate-700 dark:text-slate-200">{{ __('Vehicle brand filter') }}</span><select name="vehicle_brand_id" class="mt-1 w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">{{ __('All vehicle brands') }}</option>@foreach($vehicleBrands as $item)<option value="{{ $item->id }}" @selected((string) old('vehicle_brand_id', data_get($goal?->metric_config, 'vehicle_brand_id', '')) === (string) $item->id)>{{ $item->name }}</option>@endforeach</select></label>
    <div class="sm:col-span-2 flex justify-end"><button class="rounded-xl bg-orange-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-orange-700">{{ $editing ? __('Save changes') : __('Create Goal') }}</button></div>
</form>
